services:

  frontend:
    build:
      context: .
      dockerfile: .docker/frontend.Dockerfile
    container_name: mvp-blogpost-app-frontend
    hostname: mvp-blogpost-app-frontend
    ports:
      - 3000:3000

  backend:
    build:
      context: .
      dockerfile: .docker/backend.Dockerfile
    container_name: $BACKEND_SERVICE_NAME
    hostname: $BACKEND_SERVICE_NAME
    ports:
      - 8000:8000
    volumes:
      - ./backend:/$BACKEND_SERVICE_NAME
