services:

  frontend:
    build:
      context: .
      dockerfile: .docker/frontend.Dockerfile
    ports:
      - 3000:3000

  backend:
    build:
      context: .
      dockerfile: .docker/backend.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/mvp-blogpost-app
