services:

  frontend:
    build:
      context: .
      dockerfile: .docker/frontend.Dockerfile
    container_name: $FRONTEND_SERVICE_NAME
    environment:
      - WATCHPACK_POLLING=true
    hostname: $FRONTEND_SERVICE_NAME
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./frontend/:/app
      - /app/node_modules

  backend:
    build:
      context: .
      dockerfile: .docker/backend.Dockerfile
    container_name: $BACKEND_SERVICE_NAME
    environment:
      - CHOKIDAR_USEPOLLING=true
    hostname: $BACKEND_SERVICE_NAME
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
      - /app/node_modules
